[versions]
agp = "8.3.0-alpha03"
kotlin = "1.9.0"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
retrofit = "2.9.0"
retrofitConverter = "2.9.0"
gson = "2.10.1"
logging = "4.11.0"
constraintlayout = "2.1.4"
navigationFragmentKtx = "2.7.2"
navigationUiKtx = "2.7.2"
secretsGradlePlugin = "2.0.1"
lifecycle = "2.6.2"
archTest = "2.2.0"
testRules = "1.5.0"
testRunner = "1.5.2"
dagger = "2.48"
kotlinCoroutines = "1.7.3"
glide = "4.15.1"
paging = "3.2.1"
android_youtube_player_version = "12.0.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofitConverter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitConverter" }
logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "logging" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleLiveData = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
archCoreTest = { group = "androidx.arch.core", name = "core-testing", version.ref = "archTest"}
testRules = { group = "androidx.test", name = "rules", version.ref = "testRules"}
testRunner = { group = "androidx.test", name = "runner", version.ref = "testRunner"}
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
daggerCompiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
kotlinCoroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinCoroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
android_youtube_player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "android_youtube_player_version" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
secretsGradlePlugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

